### ISSUE TITLE
What did you mean by 'don't give back on backtrack'?

### ISSUE THREAD

**Issue by Agarwal-Nikhil** [remram44/regex-cheatsheet#18]
Could you please give an example of this?

**Comment by remram44** [comment]
A regex is matched left-to-right. Each group (by default) eats as many characters as it can, and then the next group tries to match from where we left off. If this doesn't work, a backtrack occurs, where the regex engine will try a smaller match for the first group and try the second group again.

In some cases, this might not be wanted. It is mostly an optimization: you know no match will happen, and you don't want the engine to waste its time trying every other possibility.

Simple example of what this does:
* `(a+)(ab)` will match the string `aaab` (the captured groups are `aa` and `ab`)
* `(a++)(ab)` will not match the string `aaab`, because the engine will match the first group `(a++)` to `aaa`, will not be able to match `(ab)` to `b`, and the first group will not "give back" a character `a` on backtrack.
